# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: business_api_postgres
    environment:
      POSTGRES_DB: business_api_development
      POSTGRES_USER: business_user
      POSTGRES_PASSWORD: business_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: business_api_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: business_api_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://business_user:business_password@postgres:5432/business_api_development
    command: bundle exec rails server -b 0.0.0.0

volumes:
  postgres_data: