customer:
  name:
    display_name: "顧客名"
    type: "japanese_name"
    required: true
    max_length: 100
    help_text: "顧客の正式名称を入力してください"
    placeholder: "例：田中太郎"

  email:
    display_name: "メールアドレス"
    type: "email"
    required: true
    max_length: 255
    help_text: "連絡用のメールアドレスを入力してください"
    placeholder: "例：tanaka@example.com"

  phone:
    display_name: "電話番号"
    type: "phone"
    required: false
    help_text: "ハイフン区切りで入力してください"
    placeholder: "例：03-1234-5678"

  address:
    display_name: "住所"
    type: "japanese_address"
    required: false
    max_length: 255
    help_text: "所在地を入力してください"
    placeholder: "例：東京都渋谷区..."

  company_name:
    display_name: "会社名"
    type: "japanese_name"
    required: false
    max_length: 100
    help_text: "所属会社名（個人の場合は空白）"
    placeholder: "例：株式会社サンプル"